### ISSUE TITLE
stuck at 'Reading the input and interpolating the data...'

### ISSUE THREAD

**Issue by kkivg** [NanoCalc/TMM-Sim#1]
Hello, I downloaded your Windows version of the software, and then submitted the calculation using the example file. However, it is stuck at 'Reading the input and interpolating the data...'

**Comment by OmarMesqq** [comment]
Thanks for the report! We are looking into into this issue and we'll notify here on GitHub as soon as there's a new fixed version.

**Comment by OmarMesqq** [comment]
Hey, @kkivg, just a follow up: we have released the bugfix!
Available in the [latest release](https://github.com/NanoCalc/TMM-Sim/releases/tag/1.1).
When you have the bandwith, feel free to test it and provide feedback :)
We'll release the Linux/Unix version soon.
