### ISSUE TITLE
stuck at 'Reading the input and interpolating the data...'

### ISSUE THREAD

**Issue by nhwsxds** [NanoCalc/TMM-Sim#2]
Hello, thank you for providing this tool. I have downloaded your Windows version of the software, and then submitted the calculation using the example file. However, it is stuck at 'Reading the input and interpolating the data...'. My computer version is windows 10.

**Comment by OmarMesqq** [comment]
Thanks for the report! We are looking into into this issue and we'll notify here on GitHub as soon as there's a new fixed version.

**Comment by OmarMesqq** [comment]
Hey, @nhwsxds , just a follow up: we have released the bugfix!
Available in the [latest release](https://github.com/NanoCalc/TMM-Sim/releases/tag/1.1).
When you have the bandwith, feel free to test it and provide feedback :)
We'll release the Linux/Unix version soon.

**Comment by nhwsxds** [comment]
Thank you for the update, the new version is now running properly！

**Comment by nhwsxds** [comment]
I have a few small questions and I’d like to ask you for advice.
First, regarding the simulation of BHJ devices, the designed wavelength range is 300-800 nm. If I want to test bands above 1000 nm, how should I set it up?
Additionally, for bilayer devices, the thickness of each layer can only be set from 0-100 nm. How can I increase the scanning thickness to 300 nm?

**Comment by nhwsxds** [comment]
My research interests are in semitransparent organic photovoltaic and tandem devices, and I wonder if we could collaborate on this.

**Comment by OmarMesqq** [comment]
Thank you for your interest! I am tagging @LeandroBenatto who is one of our researchers to better explain it, since I only handle computing/programming tasks.

**Comment by LeandroBenatto** [comment]
Hello, @nhwsxds, thank you for your interest in our program and for the interesting points you have raised. The simulated wavelength range is automatically defined by the refractive index spectra defined in the inputs. Considering that user-supplied refractive index spectra may cover different ranges of the light spectrum, the program automatically identifies the range of wavelengths where all spectra overlap and performs calculations within that range. The example data provided for testing the program illustrates a specific situation where the calculated range is 300 to 800 nm.

Regarding the scanning thickness of the bilayer device, there is this limitation that the thickness of each layer can only be set from 0-100 nm. We will consider changing the code to meet your need for a longer scan interval. If this is done, we will contact you.

**Comment by OmarMesqq** [comment]
@nhwsxds 
@LeandroBenatto has implemented the new feature for increasing the limitation of each layer and I've already packaged it into the new version (TMM-Sim 1.2). We also updated the data sample to illustrate how the input data should be specified.
